### ISSUE TITLE
Add "cancel" function for canceling streams

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/allo-v2#3]
1. Make the strategy contract the sender of the stream
2. Add a "cancel" function that can cancel streams via the strategy contract

**Comment by andreivladbrg** [comment]
Added in this commit fba067af142817b73821b9008c535c667030cc28

**Comment by PaulRBerg** [comment]
> Added in this commit https://github.com/sablier-labs/allo-v2/commit/fba067af142817b73821b9008c535c667030cc28

Reopening because the implementation does not increase the `poolAmount` by the refunded amount.

**Comment by andreivladbrg** [comment]
It does in the next commit 73af4b0ef452759e3c039b1682e2dda497c6357d
